# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c89787e9be5c94d1e1c5cfa249ac1997b3d0dc0f4c0a2927357198777a180b88290e3c77d830c64efbb659d1bd229aa3bba05fe7d2ecd36602220d5b6ae9e8c5

test:
  secret_key_base: 24597b99e77bd8b01c483c9112439da9f8e2221cbc21460449f991b22cd6214ec5bd77323e2b71fbc97265afd5a94cfdba26b9a5d8200d48c259ba17adc70345

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
